### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by hpk22** [sridharjena97/CoWin_Auto_Booking#1]
Hey.. It could be great if you could add cancel appointment option also.

**Comment by sridharjena97** [comment]
Hii,

I am glad to see your feedback.
Please use the script **cancel_slot.py**  to make a cancellation request.
please follow this [Link](https://github.com/sridharjena97/CoWin_Auto_Booking/blob/master/cancel_slot.py) for the source code.

Thanks & Regards,
Sridhar Jena
